-- Oracle Free DB 初期化スクリプト
-- FREEPDB1 に testuser ユーザーと USERS テーブルを作成する

ALTER SESSION SET CONTAINER = FREEPDB1;

-- ユーザー作成（既存の場合はスキップ）
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = 'TESTUSER';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER testuser IDENTIFIED BY "TestPass1!"';
    EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO testuser';
    EXECUTE IMMEDIATE 'GRANT UNLIMITED TABLESPACE TO testuser';
  END IF;
END;
/

-- USERS テーブル作成
CREATE TABLE testuser.users (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR2(100)  NOT NULL,
  email       VARCHAR2(255)  NOT NULL UNIQUE,
  age         NUMBER(3),
  created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
